site_name: Heureka's Data Station
site_author: Heureka
site_url: https://Heureka.github.io/
site_description: 知足且上进，温柔且坚定
copyright: 2025@Heureka
docs_dir: docs

nav:
  - 首页: index.md
  - 笔记:
    - STM32 Cortex-M3:
      - ADC模块: notes/stm32-cortexM3/001_ADC.md
  - 关于: about.md  

theme:
  name: material
  features:
    - navigation.tabs  # 启用标签式导航
    - navigation.top  # 顶部导航栏
    - content.tabs.link  # 内容标签页
    - header.autohide  # 滚动时自动隐藏头部
    - navigation.footer  # 底部导航
    - navigation.indexes  # 索引页支持

  font:
    text: Bitter
    code: Roboto Mono

  icon:
    logo: material/library

  logo: favicon.ico
  favicon: favicon.ico

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 关闭自动模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue 
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: 切换至夜间模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换至日间模式

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Heureka-L/
    - icon: fontawesome/brands/twitter
      link: /

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js