name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container: python:3.11
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # 获取完整历史以支持 gh-pages 分支部署
        fetch-depth: 0
      
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Configure pip mirror
      run: pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
    
    - name: Install dependencies
      run: |
        pip install mkdocs mkdocs-material 
        pip install pymdown-extensions Pygments fontawesome-markdown
    
    - name: Build site
      run: mkdocs build
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        # 如果您的源文件在子目录中，请取消注释并修改下面的路径
        # publish_branch: gh-pages
        # keep_files: false